apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: redhat-openjdk-18
  creationTimestamp: null
  labels:
    app: amq-test
  name: amq-test
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: amq-test:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/jainmnsh/amq-openshift.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: openjdk18-openshift:latest
    type: Source
  triggers:
  - type: ConfigChange
status:
  lastVersion: 0
