apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/image.dockerRepositoryCheck: 2018-03-07T22:16:13Z
  creationTimestamp: null
  generation: 149
  labels:
    app: amq-test
  name: amq-test
spec:
  lookupPolicy:
    local: false
  tags:
    referencePolicy:
      type: Source
status:
  dockerImageRepository: ""
